# Generated by Django 4.2.4 on 2023-08-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0002_registration_email_registration_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="mobile",
            field=models.BigIntegerField(default=0),
        ),
    ]
