# Generated by Django 4.2.4 on 2023-09-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0003_alter_registration_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Category_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("Category_image", models.ImageField(upload_to="upload/category/")),
            ],
        ),
    ]
