# Generated by Django 4.2.4 on 2023-09-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0004_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_desc",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("product_price", models.IntegerField()),
                ("Product_image", models.ImageField(upload_to="upload/product/")),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flipkart.category",
                    ),
                ),
            ],
        ),
    ]
