# Generated by Django 4.2.4 on 2023-09-11 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0007_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
