# Generated by Django 4.2.4 on 2023-09-11 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0009_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Product_name",
            new_name="product_name",
        ),
    ]
