# Generated by Django 4.2.4 on 2023-09-11 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0010_rename_product_name_product_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="Product_name",
        ),
    ]
