# Generated by Django 4.2.4 on 2023-09-11 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0012_delete_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
