# Generated by Django 4.2.4 on 2023-09-11 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0019_registration_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
