# Generated by Django 4.2.4 on 2023-09-11 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0021_registration_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Registration",
            new_name="Signup",
        ),
    ]
