# Generated by Django 4.2.4 on 2023-09-11 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0024_signup_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Signup",
        ),
    ]
