# Generated by Django 4.2.4 on 2023-09-18 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0026_signup_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Product_category",
            new_name="Product_categoryes",
        ),
    ]
