# Generated by Django 4.2.4 on 2023-09-18 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flipkart", "0027_rename_product_category_product_product_categoryes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Product_categoryes",
            new_name="Product_category",
        ),
    ]
